### ISSUE TITLE
self.kernel did not be changed after kernel_tensor

### ISSUE THREAD

**Issue by NingMa-AI** [ChoSungMan/DCNets-pytorch#1]
HI:
  Thank you for sharing your code.I found a strange point where self.kernel(in line 71 of file dc_module.py)  did not changed after operation on kernel_tensor.Can you help me?

**Comment by ChoSungMan** [comment]
Thank you for find strange point. 
Actually, this repo is not completed. 
Now I am trying to fix some errors & strange point.

**Comment by dev-sungman** [comment]
> HI:
> Thank you for sharing your code.I found a strange point where self.kernel(in line 71 of file dc_module.py) did not changed after operation on kernel_tensor.Can you help me?

Thank you for find strange point. 
Actually, this repo is not completed. 
Now I am trying to fix some errors & strange point.

**Comment by NingMa-AI** [comment]
Anyway,your framework helps me a lot! THANKS.

**Comment by dev-sungman** [comment]
> Anyway,your framework helps me a lot! THANKS.

For your help, I fixed some codes in dc_module.py. Thank you.
